import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable, inject, signal } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { environment } from '../../../environments/environment';
import type * as M from './models';

/**
 * Typed client for the FastAPI + DuckDB service. When the service is unreachable and snapshot
 * fallback is enabled, the same shape is read from `data/snapshot/<route>.json` (generated by
 * `api/scripts/snapshot_api.py`) so the GitHub Pages deployment still has numbers to show.
 */
@Injectable({ providedIn: 'root' })
export class ApiService {
  private readonly http = inject(HttpClient);
  /** True once a request had to fall back to a snapshot. Pages show a banner. */
  readonly usingSnapshot = signal(false);
  readonly offline = signal(false);

  async get<T>(path: string, params: object = {}): Promise<T> {
    let httpParams = new HttpParams();
    for (const [k, v] of Object.entries(params as Record<string, string | number | undefined>)) if (v !== undefined && v !== '') httpParams = httpParams.set(k, String(v));
    try {
      const value = await firstValueFrom(this.http.get<T>(`${environment.apiBase}/${path}`, { params: httpParams }));
      this.offline.set(false);
      return value;
    } catch (err) {
      if (!environment.snapshotFallback) throw err;
      this.offline.set(true);
      this.usingSnapshot.set(true);
      return firstValueFrom(this.http.get<T>(`data/snapshot/${path.replace(/\//g, '__')}.json`));
    }
  }

  // Merchandise
  merchandiseKpis(range: M.DateRange = {}) { return this.get<M.MerchandiseKpis>('merchandise/kpis', range); }
  merchandiseDaily(range: M.DateRange = {}) { return this.get<M.DailyRow[]>('merchandise/daily', range); }
  merchandiseFunnel(range: M.DateRange = {}) { return this.get<M.FunnelRow[]>('merchandise/funnel', range); }
  merchandiseByCountry(range: M.DateRange = {}, limit = 15) { return this.get<M.CountryRow[]>('merchandise/by-country', { ...range, limit }); }
  merchandiseByDevice(range: M.DateRange = {}) { return this.get<M.DeviceRow[]>('merchandise/by-device', range); }
  merchandiseSources(range: M.DateRange = {}, limit = 10) { return this.get<M.SourceRow[]>('merchandise/traffic-sources', { ...range, limit }); }
  merchandiseTopItems(range: M.DateRange = {}, limit = 12) { return this.get<M.ItemRow[]>('merchandise/top-items', { ...range, limit }); }
  merchandiseRevenueCube(range: M.DateRange = {}, countries = 8) { return this.get<M.RevenueCubeRow[]>('merchandise/revenue-cube', { ...range, countries }); }

  // Ares
  aresSummary() { return this.get<M.AresSummary>('ares/summary'); }
  aresRecordsByDomain() { return this.get<M.DomainRow[]>('ares/records-by-domain'); }
  aresAgeAtFirstObservation() { return this.get<M.AgeRow[]>('ares/person/age-at-first-observation'); }
  aresYearOfBirth() { return this.get<M.YearRow[]>('ares/person/year-of-birth'); }
  aresSex() { return this.get<M.SexRow[]>('ares/person/sex'); }
  aresRace() { return this.get<M.RaceRow[]>('ares/person/race'); }
  aresObservationLength() { return this.get<M.ObservationLengthRow[]>('ares/observation-period/length'); }
  aresObservationCumulative() { return this.get<M.ObservationCumulativeRow[]>('ares/observation-period/cumulative'); }
  aresAgeBySex() { return this.get<M.AgeBySexRow[]>('ares/observation-period/age-by-sex'); }
  aresRecordsPerMonth() { return this.get<M.RecordsPerMonthRow[]>('ares/density/records-per-month'); }
  aresRecordsPerPerson() { return this.get<M.RecordsPerPersonRow[]>('ares/density/records-per-person'); }
  aresConceptsPerPerson() { return this.get<M.ConceptsPerPersonRow[]>('ares/density/concepts-per-person'); }
  aresTopConcepts(domain: string, limit = 15) { return this.get<M.TopConceptRow[]>(`ares/concepts/${domain}/top`, { limit }); }
  aresPrevalence(domain: string, conceptId: number) { return this.get<M.PrevalenceRow[]>(`ares/concepts/${domain}/${conceptId}/prevalence`); }
  aresQuality() { return this.get<M.QualityRow[]>('ares/quality'); }
  aresQualityFailures(limit = 50) { return this.get<M.QualityFailureRow[]>('ares/quality/failures', { limit }); }

  // Atlas
  atlasStats() { return this.get<M.AtlasStats>('atlas/stats'); }
  atlasSystems() { return this.get<M.AtlasSystemRow[]>('atlas/systems'); }
  atlasParts(system?: string) { return this.get<M.AtlasPartRow[]>('atlas/parts', { system }); }
  atlasConcepts(q = '', limit = 80) { return this.get<M.AtlasConceptRow[]>('atlas/concepts', { q, limit }); }
}
