import type { GalleryChart } from './vega-charts-specs';

/* ---------------------------------------------------------------------------------------------
 * Vendored gallery specs, loaded on selection rather than inlined.
 *
 * `Specs` are the hand-built set; `Examples` are the Vega project's own gallery specs (BSD-3,
 * vega.github.io/vega/examples). Their datasets are referenced as relative `data/*.json` and are
 * NOT vendored — 56 MB of them — so `VegaChartComponent` gives the loader a baseURL pointing at
 * Vega's host. Specs whose data is inlined need nothing extra.
 * ------------------------------------------------------------------------------------------- */
export const VENDORED: GalleryChart[] = [
  { id: 'spec-beeswarm', label: 'Beeswarm Plot', group: 'Specs', url: 'data/vega/specs/beeswarm.json' },
  { id: 'spec-connected-scatter', label: 'Connected Scatter', group: 'Specs', url: 'data/vega/specs/connected-scatter.json' },
  { id: 'spec-disasters', label: 'Disasters', group: 'Specs', url: 'data/vega/specs/disasters.json' },
  { id: 'spec-parallel', label: 'Parallel Coordinates', group: 'Specs', url: 'data/vega/specs/parallel.json' },
  { id: 'spec-population', label: 'Population Pyramid', group: 'Specs', url: 'data/vega/specs/population.json' },
  { id: 'spec-qq', label: 'Q-Q Plot', group: 'Specs', url: 'data/vega/specs/qq.json' },
  { id: 'spec-scatter3D', label: 'Scatter 3D', group: 'Specs', url: 'data/vega/specs/scatter3D.json' },
  { id: 'spec-stacked_bar', label: 'Stacked Bar', group: 'Specs', url: 'data/vega/specs/stacked_bar.json' },
  { id: 'spec-stock-chart', label: 'Stock Chart', group: 'Specs', url: 'data/vega/specs/stock-chart.json' },
  { id: 'spec-titanic', label: 'Titanic', group: 'Specs', url: 'data/vega/specs/titanic.json' },
  { id: 'spec-udistrict', label: 'U-District Cuisine', group: 'Specs', url: 'data/vega/specs/udistrict.json' },
  { id: 'spec-visualization-vg', label: 'Visualization (Vega)', group: 'Specs', url: 'data/vega/specs/visualization.vg.json' },
  { id: 'spec-visualization-vl', label: 'Visualization (Vega-Lite)', group: 'Specs', url: 'data/vega/specs/visualization.vl.json' },
  { id: 'spec-warming-stripes', label: 'Warming Stripes', group: 'Specs', url: 'data/vega/specs/warming-stripes.vg.json' },
  { id: 'ex-airport-connections', label: 'Airport connections', group: 'Examples', url: 'data/vega/examples/airport-connections.vg.json' },
  { id: 'ex-annual-precipitation', label: 'Annual precipitation', group: 'Examples', url: 'data/vega/examples/annual-precipitation.vg.json' },
  { id: 'ex-annual-temperature', label: 'Annual temperature', group: 'Examples', url: 'data/vega/examples/annual-temperature.vg.json' },
  { id: 'ex-arc-diagram', label: 'Arc diagram', group: 'Examples', url: 'data/vega/examples/arc-diagram.vg.json' },
  { id: 'ex-area-chart', label: 'Area chart', group: 'Examples', url: 'data/vega/examples/area-chart.vg.json' },
  { id: 'ex-bar-chart', label: 'Bar chart', group: 'Examples', url: 'data/vega/examples/bar-chart.vg.json' },
  { id: 'ex-bar-line-toggle', label: 'Bar line toggle', group: 'Examples', url: 'data/vega/examples/bar-line-toggle.vg.json' },
  { id: 'ex-barley-trellis-plot', label: 'Barley trellis plot', group: 'Examples', url: 'data/vega/examples/barley-trellis-plot.vg.json' },
  { id: 'ex-beeswarm-plot', label: 'Beeswarm plot', group: 'Examples', url: 'data/vega/examples/beeswarm-plot.vg.json' },
  { id: 'ex-binned-scatter-plot', label: 'Binned scatter plot', group: 'Examples', url: 'data/vega/examples/binned-scatter-plot.vg.json' },
  { id: 'ex-box-plot', label: 'Box plot', group: 'Examples', url: 'data/vega/examples/box-plot.vg.json' },
  { id: 'ex-brushing-scatter-plots', label: 'Brushing scatter plots', group: 'Examples', url: 'data/vega/examples/brushing-scatter-plots.vg.json' },
  { id: 'ex-budget-forecasts', label: 'Budget forecasts', group: 'Examples', url: 'data/vega/examples/budget-forecasts.vg.json' },
  { id: 'ex-calendar-view', label: 'Calendar view', group: 'Examples', url: 'data/vega/examples/calendar-view.vg.json' },
  { id: 'ex-circle-packing', label: 'Circle packing', group: 'Examples', url: 'data/vega/examples/circle-packing.vg.json' },
  { id: 'ex-clock', label: 'Clock', group: 'Examples', url: 'data/vega/examples/clock.vg.json' },
  { id: 'ex-connected-scatter-plot', label: 'Connected scatter plot', group: 'Examples', url: 'data/vega/examples/connected-scatter-plot.vg.json' },
  { id: 'ex-contour-plot', label: 'Contour plot', group: 'Examples', url: 'data/vega/examples/contour-plot.vg.json' },
  { id: 'ex-county-unemployment', label: 'County unemployment', group: 'Examples', url: 'data/vega/examples/county-unemployment.vg.json' },
  { id: 'ex-crossfilter-flights', label: 'Crossfilter flights', group: 'Examples', url: 'data/vega/examples/crossfilter-flights.vg.json' },
  { id: 'ex-density-heatmaps', label: 'Density heatmaps', group: 'Examples', url: 'data/vega/examples/density-heatmaps.vg.json' },
  { id: 'ex-distortion-comparison', label: 'Distortion comparison', group: 'Examples', url: 'data/vega/examples/distortion-comparison.vg.json' },
  { id: 'ex-donut-chart-labelled', label: 'Donut chart labelled', group: 'Examples', url: 'data/vega/examples/donut-chart-labelled.vg.json' },
  { id: 'ex-donut-chart', label: 'Donut chart', group: 'Examples', url: 'data/vega/examples/donut-chart.vg.json' },
  { id: 'ex-dorling-cartogram', label: 'Dorling cartogram', group: 'Examples', url: 'data/vega/examples/dorling-cartogram.vg.json' },
  { id: 'ex-dot-plot', label: 'Dot plot', group: 'Examples', url: 'data/vega/examples/dot-plot.vg.json' },
  { id: 'ex-earthquakes-globe', label: 'Earthquakes globe', group: 'Examples', url: 'data/vega/examples/earthquakes-globe.vg.json' },
  { id: 'ex-earthquakes', label: 'Earthquakes', group: 'Examples', url: 'data/vega/examples/earthquakes.vg.json' },
  { id: 'ex-edge-bundling', label: 'Edge bundling', group: 'Examples', url: 'data/vega/examples/edge-bundling.vg.json' },
  { id: 'ex-error-bars', label: 'Error bars', group: 'Examples', url: 'data/vega/examples/error-bars.vg.json' },
  { id: 'ex-falkensee-population', label: 'Falkensee population', group: 'Examples', url: 'data/vega/examples/falkensee-population.vg.json' },
  { id: 'ex-flight-passengers', label: 'Flight passengers', group: 'Examples', url: 'data/vega/examples/flight-passengers.vg.json' },
  { id: 'ex-force-directed-layout', label: 'Force directed layout', group: 'Examples', url: 'data/vega/examples/force-directed-layout.vg.json' },
  { id: 'ex-global-development', label: 'Global development', group: 'Examples', url: 'data/vega/examples/global-development.vg.json' },
  { id: 'ex-grouped-bar-chart', label: 'Grouped bar chart', group: 'Examples', url: 'data/vega/examples/grouped-bar-chart.vg.json' },
  { id: 'ex-heatmap', label: 'Heatmap', group: 'Examples', url: 'data/vega/examples/heatmap.vg.json' },
  { id: 'ex-histogram-null-values', label: 'Histogram null values', group: 'Examples', url: 'data/vega/examples/histogram-null-values.vg.json' },
  { id: 'ex-histogram', label: 'Histogram', group: 'Examples', url: 'data/vega/examples/histogram.vg.json' },
  { id: 'ex-horizon-graph', label: 'Horizon graph', group: 'Examples', url: 'data/vega/examples/horizon-graph.vg.json' },
  { id: 'ex-hypothetical-outcome-plots', label: 'Hypothetical outcome plots', group: 'Examples', url: 'data/vega/examples/hypothetical-outcome-plots.vg.json' },
  { id: 'ex-interactive-legend', label: 'Interactive legend', group: 'Examples', url: 'data/vega/examples/interactive-legend.vg.json' },
  { id: 'ex-job-voyager', label: 'Job voyager', group: 'Examples', url: 'data/vega/examples/job-voyager.vg.json' },
  { id: 'ex-labeled-scatter-plot', label: 'Labeled scatter plot', group: 'Examples', url: 'data/vega/examples/labeled-scatter-plot.vg.json' },
  { id: 'ex-line-chart', label: 'Line chart', group: 'Examples', url: 'data/vega/examples/line-chart.vg.json' },
  { id: 'ex-loess-regression', label: 'Loess regression', group: 'Examples', url: 'data/vega/examples/loess-regression.vg.json' },
  { id: 'ex-map-with-tooltip', label: 'Map with tooltip', group: 'Examples', url: 'data/vega/examples/map-with-tooltip.vg.json' },
  { id: 'ex-nested-bar-chart', label: 'Nested bar chart', group: 'Examples', url: 'data/vega/examples/nested-bar-chart.vg.json' },
  { id: 'ex-overview-plus-detail', label: 'Overview plus detail', group: 'Examples', url: 'data/vega/examples/overview-plus-detail.vg.json' },
  { id: 'ex-packed-bubble-chart', label: 'Packed bubble chart', group: 'Examples', url: 'data/vega/examples/packed-bubble-chart.vg.json' },
  { id: 'ex-pacman', label: 'Pacman', group: 'Examples', url: 'data/vega/examples/pacman.vg.json' },
  { id: 'ex-parallel-coordinates', label: 'Parallel coordinates', group: 'Examples', url: 'data/vega/examples/parallel-coordinates.vg.json' },
  { id: 'ex-pi-monte-carlo', label: 'Pi monte carlo', group: 'Examples', url: 'data/vega/examples/pi-monte-carlo.vg.json' },
  { id: 'ex-pie-chart', label: 'Pie chart', group: 'Examples', url: 'data/vega/examples/pie-chart.vg.json' },
  { id: 'ex-platformer', label: 'Platformer', group: 'Examples', url: 'data/vega/examples/platformer.vg.json' },
  { id: 'ex-population-pyramid', label: 'Population pyramid', group: 'Examples', url: 'data/vega/examples/population-pyramid.vg.json' },
  { id: 'ex-probability-density', label: 'Probability density', group: 'Examples', url: 'data/vega/examples/probability-density.vg.json' },
  { id: 'ex-projections', label: 'Projections', group: 'Examples', url: 'data/vega/examples/projections.vg.json' },
  { id: 'ex-quantile-dot-plot', label: 'Quantile dot plot', group: 'Examples', url: 'data/vega/examples/quantile-dot-plot.vg.json' },
  { id: 'ex-quantile-quantile-plot', label: 'Quantile quantile plot', group: 'Examples', url: 'data/vega/examples/quantile-quantile-plot.vg.json' },
  { id: 'ex-radar-chart', label: 'Radar chart', group: 'Examples', url: 'data/vega/examples/radar-chart.vg.json' },
  { id: 'ex-radial-plot', label: 'Radial plot', group: 'Examples', url: 'data/vega/examples/radial-plot.vg.json' },
  { id: 'ex-radial-tree-layout', label: 'Radial tree layout', group: 'Examples', url: 'data/vega/examples/radial-tree-layout.vg.json' },
  { id: 'ex-regression', label: 'Regression', group: 'Examples', url: 'data/vega/examples/regression.vg.json' },
  { id: 'ex-reorderable-matrix', label: 'Reorderable matrix', group: 'Examples', url: 'data/vega/examples/reorderable-matrix.vg.json' },
  { id: 'ex-scatter-plot-null-values', label: 'Scatter plot null values', group: 'Examples', url: 'data/vega/examples/scatter-plot-null-values.vg.json' },
  { id: 'ex-scatter-plot', label: 'Scatter plot', group: 'Examples', url: 'data/vega/examples/scatter-plot.vg.json' },
  { id: 'ex-serpentine-timeline', label: 'Serpentine timeline', group: 'Examples', url: 'data/vega/examples/serpentine-timeline.vg.json' },
  { id: 'ex-stacked-area-chart', label: 'Stacked area chart', group: 'Examples', url: 'data/vega/examples/stacked-area-chart.vg.json' },
  { id: 'ex-stacked-bar-chart', label: 'Stacked bar chart', group: 'Examples', url: 'data/vega/examples/stacked-bar-chart.vg.json' },
  { id: 'ex-stock-index-chart', label: 'Stock index chart', group: 'Examples', url: 'data/vega/examples/stock-index-chart.vg.json' },
  { id: 'ex-sunburst', label: 'Sunburst', group: 'Examples', url: 'data/vega/examples/sunburst.vg.json' },
  { id: 'ex-table-scrollbar', label: 'Table scrollbar', group: 'Examples', url: 'data/vega/examples/table-scrollbar.vg.json' },
  { id: 'ex-time-units', label: 'Time units', group: 'Examples', url: 'data/vega/examples/time-units.vg.json' },
  { id: 'ex-timelines', label: 'Timelines', group: 'Examples', url: 'data/vega/examples/timelines.vg.json' },
  { id: 'ex-top-k-plot-with-others', label: 'Top k plot with others', group: 'Examples', url: 'data/vega/examples/top-k-plot-with-others.vg.json' },
  { id: 'ex-top-k-plot', label: 'Top k plot', group: 'Examples', url: 'data/vega/examples/top-k-plot.vg.json' },
  { id: 'ex-tree-layout', label: 'Tree layout', group: 'Examples', url: 'data/vega/examples/tree-layout.vg.json' },
  { id: 'ex-treemap', label: 'Treemap', group: 'Examples', url: 'data/vega/examples/treemap.vg.json' },
  { id: 'ex-u-district-cuisine', label: 'U district cuisine', group: 'Examples', url: 'data/vega/examples/u-district-cuisine.vg.json' },
  { id: 'ex-violin-plot', label: 'Violin plot', group: 'Examples', url: 'data/vega/examples/violin-plot.vg.json' },
  { id: 'ex-volcano-contours', label: 'Volcano contours', group: 'Examples', url: 'data/vega/examples/volcano-contours.vg.json' },
  { id: 'ex-warming-stripes', label: 'Warming stripes', group: 'Examples', url: 'data/vega/examples/warming-stripes.vg.json' },
  { id: 'ex-watch', label: 'Watch', group: 'Examples', url: 'data/vega/examples/watch.vg.json' },
  { id: 'ex-weekly-temperature', label: 'Weekly temperature', group: 'Examples', url: 'data/vega/examples/weekly-temperature.vg.json' },
  { id: 'ex-wheat-and-wages', label: 'Wheat and wages', group: 'Examples', url: 'data/vega/examples/wheat-and-wages.vg.json' },
  { id: 'ex-wheat-plot', label: 'Wheat plot', group: 'Examples', url: 'data/vega/examples/wheat-plot.vg.json' },
  { id: 'ex-wind-vectors', label: 'Wind vectors', group: 'Examples', url: 'data/vega/examples/wind-vectors.vg.json' },
  { id: 'ex-word-cloud', label: 'Word cloud', group: 'Examples', url: 'data/vega/examples/word-cloud.vg.json' },
  { id: 'ex-world-map', label: 'World map', group: 'Examples', url: 'data/vega/examples/world-map.vg.json' },
  { id: 'ex-zoomable-binned-plot', label: 'Zoomable binned plot', group: 'Examples', url: 'data/vega/examples/zoomable-binned-plot.vg.json' },
  { id: 'ex-zoomable-circle-packing', label: 'Zoomable circle packing', group: 'Examples', url: 'data/vega/examples/zoomable-circle-packing.vg.json' },
  { id: 'ex-zoomable-scatter-plot', label: 'Zoomable scatter plot', group: 'Examples', url: 'data/vega/examples/zoomable-scatter-plot.vg.json' },
  { id: 'ex-zoomable-world-map', label: 'Zoomable world map', group: 'Examples', url: 'data/vega/examples/zoomable-world-map.vg.json' },
];
